'use client';
import Link from 'next/link';
import { ArrowRight, CalendarDays, LockKeyhole, MessageCircle, Sparkles } from 'lucide-react';
import { Shell } from '@/components/ui';
import { useApp } from '@/components/app-provider';

export default function Home() {
  const { data, ready } = useApp();
  if (!ready) return <Shell><div className="loading">Making a calm space…</div></Shell>;
  const done = data.sessions.filter(s => s.completedAt).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const last = done[0];
  if (!last) return <Shell><section className="hero"><div className="ambient a"/><div className="ambient b"/><div className="eyebrow"><Sparkles size={15}/> A gentle pause for two</div><h1>Meet each other<br/><em>where you are.</em></h1><p className="lead">A private space for honest reflection and stronger connection.</p><div className="actions actions-stack"><Link className="btn primary" href="/setup">Start a check-in <ArrowRight size={18}/></Link><Link className="btn primary together-cta" href="/together"><MessageCircle size={18}/> Questions for two <ArrowRight size={18}/></Link><a className="btn secondary" href="#how">How it works</a></div><div className="privacy-note"><LockKeyhole size={16}/>Your answers stay on this device.</div></section><section id="how" className="steps"><article><span>01</span><h3>Reflect privately</h3><p>Each partner answers the same gentle prompts in their own time.</p></article><article><span>02</span><h3>Notice together</h3><p>See shared ground and different perspectives without judgment.</p></article><article><span>03</span><h3>Choose one step</h3><p>Turn your conversation into a small intention for the week.</p></article></section><p className="disclaimer">Together supports relationship reflection and is not a substitute for professional counselling or emergency help.</p></Shell>;
  const ratings = last.answers.filter(a => a.questionId === 'connection').map(a => Number(a.value));
  return <Shell><section className="dash-head"><div><div className="eyebrow">Your shared space</div><h1>Good to see you both.</h1><p>Make a little room to notice what matters.</p></div><div className="actions"><Link href="/check-in" className="btn primary">New check-in <ArrowRight size={18}/></Link><Link href="/together" className="btn primary together-cta"><MessageCircle size={18}/> Questions for two <ArrowRight size={18}/></Link></div></section>{last.sharedIntention&&<section className="intention-card"><div><span className="mini">CURRENT INTENTION</span><h2>“{last.sharedIntention.shared}”</h2><p>{last.partners[0].displayName}: {last.sharedIntention.actionA}<br/>{last.partners[1].displayName}: {last.sharedIntention.actionB}</p></div><Sparkles size={28}/></section>}<section className="grid2"><article className="card"><div className="card-title"><h2>Latest reflection</h2><span>{new Date(last.completedAt!).toLocaleDateString()}</span></div><div className="rating-big">{ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1):'—'}<small>/ 5</small></div><p>Average connection rating, shown as reflection—not a relationship score.</p></article><article className="card"><div className="card-title"><h2>Next check-in</h2><CalendarDays/></div><h3>{data.settings.checkInFrequency==='none'?'Whenever it feels useful':data.settings.checkInFrequency==='weekly'?'In about one week':data.settings.checkInFrequency==='biweekly'?'In about two weeks':'In about one month'}</h3><p>Your schedule is a gentle reminder, never a deadline.</p></article></section></Shell>;
}
